name: Build MSI Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 安装 Clang 和 LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "15"

      - name: 切换版本
        run: git checkout ${{ github.event.inputs.tag }}

      - name: python环境设置
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Nuitka编译
        run: |
          python -m nuitka --standalone --show-progress --plugin-enable=pyside6 `
          src\main.py `
          --clang `
          --windows-console-mode=disable `
          --low-memory `
          --windows-icon-from-ico=.\src\LuxDown.ico `
          --windows-company-name="hhelibe" `
          --windows-product-name="LuxDown" `
          --windows-file-version=1.0.0.0 `
          --windows-product-version=1.0.0.0 `
          --windows-file-description=" 这是一款用于下载视频的软件" `
          --output-filename=LuxDown --output-dir=build --assume-yes-for-downloads `
          --jobs=1

      - name: 安装 WiX Toolset
        run: dotnet tool install --global wix

      - name: 下载ffmpeg
        run: |
          Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z" -OutFile "ffmpeg.7z"`
          7z x ffmpeg.7z -offmpeg_extracted -y
          $sourceFolder = Get-ChildItem -Directory ffmpeg_extracted | Select-Object -First 1
          Copy-Item "$($sourceFolder.FullName)\*" "build\main.dist\ffmpeg\" -Recurse -Force

      - name: 下载deno
        run: |
          Invoke-WebRequest -Uri "https://github.com/denoland/deno/releases/download/v2.7.14/deno-x86_64-pc-windows-msvc.zip" -OutFile "deno.zip"
          Expand-Archive -Path deno.zip -DestinationPath deno_extracted
          New-Item -ItemType Directory -Path "build\main.dist\deno" -Force
          Copy-Item deno_extracted\* "build\main.dist\deno\" -Recurse -Force

      #- name: 翻译
      #  run: |
      #    Get-ChildItem -Path src -Filter *.ts | ForEach-Object { pyside6-lrelease $_.FullName }

      #- name: 复制翻译文件到打包目录
      #  run: |
      #    Copy-Item src/*.qm "build\main.dist" -Force

      - name: 构建msi安装包
        run: |
          wix extension add WixToolset.Util.wixext
          wix build installer.wxs -o LuxDown-x64-${{ github.event.inputs.tag }}.msi -arch x64

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: LuxDown-x64-${{ github.event.inputs.tag }}.msi
          path: 'LuxDown-x64-${{ github.event.inputs.tag }}.msi'